default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
        exclude: ^(backend/migrations/)
      - id: trailing-whitespace

  # ruff - linting + formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.9"
    hooks:
      - id: ruff
        name: ruff
        exclude: ^(backend/migrations/|backend/.*/tests/)
        args: ["--fix"]

  # mypy - type checking (updated for FastAPI)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: mypy
        additional_dependencies:
          - uv
          - fastapi
          - types-requests
          - types-pytz
          - types-Pillow
          - types-python-dateutil
          - types-redis
          - sqlmodel
          - pydantic-settings
          - celery-stubs
          - minio
          - pyjwt
          - fastapi_pagination
          - fastapi_async_sqlalchemy
          - fastapi_cache
          - oso
          - sqlalchemy_utils
          - celery_sqlalchemy_scheduler
          - bcrypt
        exclude: ^(backend/migrations/|backend/.*/tests/)
        args:
          - --explicit-package-bases
          - --disable-error-code=import-not-found
          - --disable-error-code=import-untyped

  # docformatter - format docstrings
  - repo: https://github.com/pycqa/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        name: docformatter
        args:
          [
            -r,
            -i,
            --pre-summary-newline,
            --make-summary-multi-line,
            --wrap-summaries,
            "120",
            --wrap-descriptions,
            "120",
            backend,
            scripts,
          ]

  # bandit - security scanner
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        name: bandit
        exclude: ^(backend/migrations/|backend/.*/tests/)
        args:
          - -r
          - --exclude
          - backend/migrations,backend/tests
          - backend

  # prettier - for JS, CSS, JSON, Markdown
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: ^poetry.lock
