services:
  postgres:
    image: bitnami/postgresql:17.4.0
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
    networks:
      - aegis-network
    shm_size: 1g
    container_name: postgres-aegis
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USER}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}

  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
    networks:
      - aegis-network
    container_name: redis-aegis
    env_file:
      - .env

  minio_server:
    image: minio/minio:latest
    restart: always
    container_name: minio_server
    volumes:
      - ./minio/data:/data
    expose:
      - 9000
      - 9091
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: http://stash.localhost
    command: "server /data --console-address ':9090'"

volumes:
  postgres_data:

networks:
  aegis-network:
    external: true
