services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aegis-network
    shm_size: 1g
    container_name: postgres-aegis

  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
    networks:
      - aegis-network
    container_name: redis-aegis

volumes:
  postgres_data:

networks:
  aegis-network:
    external: true
