services:
  database:
    image: bitnami/postgresql:17.4.0
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
    networks:
      - aegis-network
    shm_size: 1g
    container_name: postgres-aegis
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USER}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}

  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
    networks:
      - aegis-network
    container_name: redis-aegis
    env_file:
      - .env

  minio_server:
    image: minio/minio:latest
    restart: always
    container_name: minio_server
    volumes:
      - ./minio/data:/data
    expose:
      - 9000
      - 9091
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: http://stash.localhost
    command: "server /data --console-address ':9090'"

  index:
    image: vespaengine/vespa:8.277.17
    restart: always
    ports:
      - "19071"
      - "8081"
    volumes:
      - vespa_volume:/opt/vespa/var
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"

  clickhouse:
    image: clickhouse/clickhouse-server:24.4.1
    container_name: clickhouse
    environment:
      CLICKHOUSE_PASSWORD: ${OPENLIT_DB_PASSWORD:-OPENLIT}
      CLICKHOUSE_USER: ${OPENLIT_DB_USER:-default}
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
    restart: always

  openlit:
    image: ghcr.io/openlit/openlit:latest
    container_name: openlit
    environment:
      TELEMETRY_ENABLED: true
      INIT_DB_HOST: clickhouse
      INIT_DB_PORT: 8123
      INIT_DB_DATABASE: ${OPENLIT_DB_NAME:-openlit}
      INIT_DB_USERNAME: ${OPENLIT_DB_USER:-default}
      INIT_DB_PASSWORD: ${OPENLIT_DB_PASSWORD:-OPENLIT}
      SQLITE_DATABASE_URL: file:/app/client/data/data.db
      PORT: ${PORT:-3000}
      DOCKER_PORT: ${PORT:-3000}
    ports:
      - "${PORT:-3000}:${DOCKER_PORT:-3000}"
    depends_on:
      - clickhouse
    volumes:
      - openlit-data:/app/client/data
    restart: always

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.94.0
    container_name: otel-collector
    environment:
      INIT_DB_HOST: clickhouse
      INIT_DB_PORT: 9000
      INIT_DB_DATABASE: ${OPENLIT_DB_NAME:-openlit}
      INIT_DB_USERNAME: ${OPENLIT_DB_USER:-default}
      INIT_DB_PASSWORD: ${OPENLIT_DB_PASSWORD:-OPENLIT}
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "55679:55679"
    depends_on:
      - clickhouse
    volumes:
      - ./assets/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    restart: always

  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    ########################################
    # Uncomment these lines to start proxy with a config.yaml file ##
    volumes:
      - ./assets/litellm_config.yaml:/app/config.yaml
    command:
      - "--config=/app/config.yaml"
    #############################################
    networks:
      - aegis-network
    ports:
      - "4000:4000" # Map the container port to the host, change the host port if necessary
    env_file:
      - .env # Load local .env file

volumes:
  postgres_data:
  vespa_volume:
  clickhouse-data:
  openlit-data:

networks:
  aegis-network:
    external: true
