"""
Sec migration.

Revision ID: 0bc086a6899d
Revises: 4f905f2dada6
Create Date: 2025-02-24 11:48:13.564042
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '0bc086a6899d'
down_revision: Union[str, None] = '4f905f2dada6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
