"""
LLMStub models.

Revision ID: 31cc760e0a38
Revises: 3302d421cb4d
Create Date: 2025-04-16 02:25:36.978590
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '31cc760e0a38'
down_revision: Union[str, None] = '3302d421cb4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LLMStubReplaySequence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_LLMStubReplaySequence_id'), 'LLMStubReplaySequence', ['id'], unique=False)
    op.create_index(op.f('ix_LLMStubReplaySequence_name'), 'LLMStubReplaySequence', ['name'], unique=False)
    op.create_table('LLMStubRequestResponse',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_params', sa.JSON(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('request_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_LLMStubRequestResponse_id'), 'LLMStubRequestResponse', ['id'], unique=False)
    op.create_index(op.f('ix_LLMStubRequestResponse_request_hash'), 'LLMStubRequestResponse', ['request_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_LLMStubRequestResponse_request_hash'), table_name='LLMStubRequestResponse')
    op.drop_index(op.f('ix_LLMStubRequestResponse_id'), table_name='LLMStubRequestResponse')
    op.drop_table('LLMStubRequestResponse')
    op.drop_index(op.f('ix_LLMStubReplaySequence_name'), table_name='LLMStubReplaySequence')
    op.drop_index(op.f('ix_LLMStubReplaySequence_id'), table_name='LLMStubReplaySequence')
    op.drop_table('LLMStubReplaySequence')
    # ### end Alembic commands ###
