"""
current_index.

Revision ID: 4fc5b491fca0
Revises: 31cc760e0a38
Create Date: 2025-04-16 06:01:35.668927
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '4fc5b491fca0'
down_revision: Union[str, None] = '31cc760e0a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LLMStubReplaySequence', sa.Column('current_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LLMStubReplaySequence', 'current_index')
    # ### end Alembic commands ###
