"""
Removed hero.

Revision ID: 87f264cf9918
Revises: c8952e27833c
Create Date: 2025-02-25 00:54:17.798824
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87f264cf9918'
down_revision: Union[str, None] = 'c8952e27833c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Hero_age', table_name='Hero')
    op.drop_index('ix_Hero_id', table_name='Hero')
    op.drop_index('ix_Hero_name', table_name='Hero')
    op.drop_table('Hero')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Hero',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secret_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], name='Hero_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], name='Hero_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Hero_pkey')
    )
    op.create_index('ix_Hero_name', 'Hero', ['name'], unique=False)
    op.create_index('ix_Hero_id', 'Hero', ['id'], unique=False)
    op.create_index('ix_Hero_age', 'Hero', ['age'], unique=False)
    # ### end Alembic commands ###
