"""
current_index.

Revision ID: 8f3ca9e05e0a
Revises: 4fc5b491fca0
Create Date: 2025-04-16 07:03:08.395770
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '8f3ca9e05e0a'
down_revision: Union[str, None] = '4fc5b491fca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LLMStubReplaySequence', sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('LLMStubReplaySequence', sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('LLMStubReplaySequence', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_LLMStubReplaySequence_name', table_name='LLMStubReplaySequence')
    op.create_index(op.f('ix_LLMStubReplaySequence_model'), 'LLMStubReplaySequence', ['model'], unique=False)
    op.drop_column('LLMStubReplaySequence', 'name')
    op.drop_column('LLMStubReplaySequence', 'description')
    op.alter_column('LLMStubRequestResponse', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('LLMStubRequestResponse', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('LLMStubRequestResponse', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_LLMStubRequestResponse_model'), 'LLMStubRequestResponse', ['model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_LLMStubRequestResponse_model'), table_name='LLMStubRequestResponse')
    op.alter_column('LLMStubRequestResponse', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('LLMStubRequestResponse', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('LLMStubRequestResponse', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('LLMStubReplaySequence', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('LLMStubReplaySequence', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_LLMStubReplaySequence_model'), table_name='LLMStubReplaySequence')
    op.create_index('ix_LLMStubReplaySequence_name', 'LLMStubReplaySequence', ['name'], unique=False)
    op.alter_column('LLMStubReplaySequence', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('LLMStubReplaySequence', 'model')
    op.drop_column('LLMStubReplaySequence', 'provider')
    # ### end Alembic commands ###
