"""
API key.

Revision ID: 985c95f365cf
Revises: 6ad93886d940
Create Date: 2025-03-22 20:24:38.547899
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '985c95f365cf'
down_revision: Union[str, None] = '6ad93886d940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('APIKey',
    sa.Column('key_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preview', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hashed_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_APIKey_hashed_key'), 'APIKey', ['hashed_key'], unique=False)
    op.create_index(op.f('ix_APIKey_id'), 'APIKey', ['id'], unique=False)
    op.create_index(op.f('ix_APIKey_is_active'), 'APIKey', ['is_active'], unique=False)
    op.create_index(op.f('ix_APIKey_key_id'), 'APIKey', ['key_id'], unique=True)
    op.create_index(op.f('ix_APIKey_name'), 'APIKey', ['name'], unique=False)
    op.create_index(op.f('ix_APIKey_preview'), 'APIKey', ['preview'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_APIKey_preview'), table_name='APIKey')
    op.drop_index(op.f('ix_APIKey_name'), table_name='APIKey')
    op.drop_index(op.f('ix_APIKey_key_id'), table_name='APIKey')
    op.drop_index(op.f('ix_APIKey_is_active'), table_name='APIKey')
    op.drop_index(op.f('ix_APIKey_id'), table_name='APIKey')
    op.drop_index(op.f('ix_APIKey_hashed_key'), table_name='APIKey')
    op.drop_table('APIKey')
    # ### end Alembic commands ###
