"""
M2M Client.

Revision ID: ab0f108862d3
Revises: e3fa06fcb6ed
Create Date: 2025-02-28 22:36:34.144493
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'ab0f108862d3'
down_revision: Union[str, None] = 'e3fa06fcb6ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('M2MClient',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('service_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('hashed_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_M2MClient_client_id'), 'M2MClient', ['client_id'], unique=True)
    op.create_index(op.f('ix_M2MClient_hashed_secret'), 'M2MClient', ['hashed_secret'], unique=False)
    op.create_index(op.f('ix_M2MClient_id'), 'M2MClient', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_M2MClient_id'), table_name='M2MClient')
    op.drop_index(op.f('ix_M2MClient_hashed_secret'), table_name='M2MClient')
    op.drop_index(op.f('ix_M2MClient_client_id'), table_name='M2MClient')
    op.drop_table('M2MClient')
    # ### end Alembic commands ###
