"""
Initial migrations.

Revision ID: c5440e2734bb
Revises: 1dc8641b8916
Create Date: 2025-03-03 02:03:21.844524
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5440e2734bb'
down_revision: Union[str, None] = '1dc8641b8916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Team_id', table_name='Team')
    op.drop_index('ix_Team_name', table_name='Team')
    op.drop_table('Team')
    op.add_column('Group', sa.Column('tenant_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_Group_tenant_id'), 'Group', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'Group', 'Tenant', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Group', type_='foreignkey')
    op.drop_index(op.f('ix_Group_tenant_id'), table_name='Group')
    op.drop_column('Group', 'tenant_id')
    op.create_table('Team',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('headquarters', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], name='Team_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Team_pkey')
    )
    op.create_index('ix_Team_name', 'Team', ['name'], unique=False)
    op.create_index('ix_Team_id', 'Team', ['id'], unique=False)
    # ### end Alembic commands ###
