"""
API key.

Revision ID: cff748b57638
Revises: 985c95f365cf
Create Date: 2025-03-22 20:47:31.759639
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'cff748b57638'
down_revision: Union[str, None] = '985c95f365cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('APIKey', 'preview',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('APIKey', 'preview',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
